"""
markdown_writer.py — Builds and rewrites the session markdown file.

Watches the TopicAnalyzer's topics list and re-renders the full markdown
file on every update. Called from TopicAnalyzer via a thread-safe callback.
"""

import os
import threading
from datetime import datetime
from pathlib import Path

import config
from transcriber import _fmt_time
from topic_analyzer import TopicSection


class MarkdownWriter:
    """
    Renders the list of TopicSection objects to a markdown file.
    Thread-safe: multiple rapid on_update() calls are coalesced so the file
    is not written more often than necessary.
    """

    def __init__(self, topics: list, lock: threading.Lock, session_start: datetime):
        self._topics = topics
        self._lock = lock
        self._session_start = session_start
        self._output_path = self._make_path(session_start)
        self._dirty = threading.Event()
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None

        os.makedirs(config.OUTPUT_DIR, exist_ok=True)
        print(f"[MarkdownWriter] Output → {self._output_path}")

    @property
    def output_path(self) -> str:
        return str(self._output_path)

    def start(self) -> None:
        self._stop_event.clear()
        self._thread = threading.Thread(target=self._write_loop, daemon=True, name="MarkdownWriter")
        self._thread.start()

    def stop(self) -> None:
        self._dirty.set()          # flush any pending write
        self._stop_event.set()
        if self._thread:
            self._thread.join(timeout=15)

    def notify(self) -> None:
        """Signal that topics have changed and the file should be rewritten."""
        self._dirty.set()

    def _write_loop(self) -> None:
        while not self._stop_event.is_set():
            triggered = self._dirty.wait(timeout=1.0)
            if triggered:
                self._dirty.clear()
                self._render()
        self._render()  # final flush
        print("[MarkdownWriter] Stopped.")

    def _render(self) -> None:
        try:
            with self._lock:
                topics_snapshot = list(self._topics)
            content = self._build_markdown(topics_snapshot)
            tmp_path = self._output_path.with_suffix(".tmp")
            tmp_path.write_text(content, encoding="utf-8")
            tmp_path.replace(self._output_path)
        except Exception as e:
            print(f"[MarkdownWriter] Render error: {e}")

    def _build_markdown(self, topics: list[TopicSection]) -> str:
        date_str = self._session_start.strftime("%Y-%m-%d %H:%M")
        lines: list[str] = [
            f"# 📚 Course Transcript — {date_str}",
            "",
            "> Auto-generated by course-summarizer · transcription by Whisper · summaries by Ollama",
            "",
            "---",
            "",
        ]

        for topic in topics:
            start_fmt = _fmt_time(topic.start_time)
            status = "✅" if topic.is_finalized else "🔄"
            lines += [
                f"## {status} {topic.title}",
                f"*Started at {start_fmt}*",
                "",
            ]

            if topic.summary:
                lines += [
                    "### Summary",
                    "",
                    topic.summary,
                    "",
                ]
            elif topic.is_finalized:
                lines += ["### Summary", "", "_Summarizing…_", ""]

            if topic.segments:
                lines += ["### Transcript", ""]
                for seg in topic.segments:
                    t = _fmt_time(seg.start_time)
                    lines += [f"**`{t}`**", "", seg.text, ""]

            lines += ["---", ""]

        return "\n".join(lines)

    @staticmethod
    def _make_path(session_start: datetime) -> Path:
        filename = session_start.strftime("course_%Y-%m-%d_%H-%M.md")
        return Path(config.OUTPUT_DIR) / filename
